// Imports the TypeScript type used for defining page metadata.
// Docs: https://nextjs.org/docs/app/getting-started/metadata-and-og-images
import type { Metadata } from "next";

// Imports optimized Google fonts using Next.js font system.
// Docs: https://nextjs.org/docs/app/getting-started/fonts
import { Geist, Geist_Mono } from "next/font/google";

// Imports global CSS for the entire application.
import "./globals.css";

// Configures the main sans-serif font.
// The variable value creates a CSS variable that can be used by Tailwind/CSS.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configures the monospace font, usually useful for code-style text.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata used by Next.js to generate <title> and meta description tags.
// This helps with SEO, browser tab titles, and sharing previews.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is the top-level wrapper for the whole app.
// In the App Router, app/layout.tsx wraps every page.
// Docs: https://nextjs.org/docs/app/getting-started/layouts-and-pages
export default function RootLayout({
  children,
}: Readonly<{
  // children represents the current page being displayed.
  // For example, app/page.tsx is inserted where {children} appears.
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Applies both font variables globally.
      // h-full makes the html element full height.
      // antialiased smooths font rendering.
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* body wraps all visible page content.
          min-h-full helps the page fill the available height.
          flex flex-col stacks content vertically. */}
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}